parameters:
  stinger_soft.solr_entity_search.search_service.class: 'StingerSoft\SolrEntitySearchBundle\Services\SearchService'
  stinger_soft.solr_entity_search.knp_query_subscriber.class: 'StingerSoft\SolrEntitySearchBundle\Services\SolariumQuerySubscriber'

  
services:
  _defaults:
    autoconfigure: true
    autowire: true
    public: false

  StingerSoft\SolrEntitySearchBundle\Command\:
    resource: '../../Command/*'
    autowire: true
    autoconfigure: true
    public: false
    lazy: true

  StingerSoft\SolrEntitySearchBundle\Services\SearchService:
    alias: stinger_soft.solr_entity_search.search_service


  stinger_soft.solr_entity_search.search_service:
    class: '%stinger_soft.solr_entity_search.search_service.class%'

  stinger_soft.solr_entity_search.knp_query_subscriber:
    class: '%stinger_soft.solr_entity_search.knp_query_subscriber.class%'
    tags:
      - { name: 'knp_paginator.subscriber' }
